name: ideavista
description: "An inspiration application."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
  google_fonts: ^6.2.1
  auto_route: ^8.3.0

  # Utility
  easy_logger: ^0.0.2
  equatable: ^2.0.5
  logger: ^2.4.0
  get_it: ^7.7.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  convex_bottom_bar: ^3.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter  
  
  # Core Dev Dependencies
  very_good_analysis: ^6.0.0
  auto_route_generator: ^8.1.0
  build_runner: ^2.4.11
  mockito: ^5.4.4
  bloc_test: ^9.1.4
  network_image_mock: ^2.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/